import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Footer from "~/components/Footer";
import styles from "../styles/index.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Samuel Palacios Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section
        id="hero"
        className={`mt-20 pt-20 ${styles.minHeight as string}`}
      >
        <span className="text-xl font-semibold tracking-tight text-cyan-400">
          Hi, I&apos;m
        </span>
        <h1 className="mt-1 text-4xl font-semibold tracking-tight text-white">
          Samuel Palacios
        </h1>
        <h2 className="text-2xl font-semibold text-gray-400">
          a full-stack developer who loves to build things with code.
        </h2>
        <p className="mt-6 text-base font-normal text-gray-400">
          I&apos;m a software engineering student who loves to build things for
          the web. Through constant practice and learning, I create products
          that not only provide value to users, but are also exceptional and
          user-friendly.
        </p>
        {/* <div className="social-media-links-wrapper">
          <div className="flex flex-row justify-center justify-items-center"></div>
        </div> */}
        <div className="btn-wrapper">
          <Link
            href="#projects"
            className="hover:to-blue-7 mt-8 inline-block transform rounded-xl bg-gradient-to-br from-cyan-400 to-blue-600 px-5 py-3 text-sm font-semibold text-white transition duration-300 ease-in-out hover:-translate-y-1 hover:shadow-lg"
          >
            See my projects
          </Link>
        </div>
      </section>

      <section id="about" className="pt-20">
        <h1 className="mb-4 text-2xl font-semibold text-white">About Me</h1>
        <p className="text-base font-normal text-gray-400">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. A molestiae
          eveniet excepturi, corporis odio quisquam facilis et error eaque porro
          doloremque minima ipsam quam vel itaque alias illum ea repudiandae
          quae explicabo. Animi adipisci veritatis maxime natus expedita rem
          reiciendis.
        </p>
      </section>
      <section id="projects" className="pt-20">
        <h1 className="mb-4 text-2xl font-semibold text-white">Projects</h1>
        <p className="text-base font-normal text-gray-400">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. A molestiae
          eveniet excepturi, corporis odio quisquam facilis et error eaque porro
          doloremque minima ipsam quam vel itaque alias illum ea repudiandae
          quae explicabo. Animi adipisci veritatis maxime natus expedita rem
          reiciendis.
        </p>
      </section>
      <section id="contact" className="pt-20">
        <h1 className="mb-4 text-2xl font-semibold text-white">Contact</h1>
        <p className="text-base font-normal text-gray-400">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. A molestiae
          eveniet excepturi, corporis odio quisquam facilis et error eaque porro
          doloremque minima ipsam quam vel itaque alias illum ea repudiandae
          quae explicabo. Animi adipisci veritatis maxime natus expedita rem
          reiciendis.
        </p>
      </section>
      <Footer />
    </>
  );
};

export default Home;
