import { type NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import Hero from "../components/Hero";
const MainContent = dynamic(() => import("../components/MainContent"));

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Samuel Palacios Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <MainContent />
    </>
  );
};

export default Home;
